engines:
  checkstyle:
    enabled: true
    exclude_patterns:
      - "**/module-info.java"
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false