engines:
  checkstyle:
    enabled: true
    exclude_patterns:
      - "**/module-info.java"
      - "module-info.java"
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocParagraphCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false #Disabled as the check is not working properly (maybe due to \n\r stuff)