engines:
  checkstyle:
    enabled: true
    exclude_patterns:
      - "**/module-info.java"
      - "module-info.java"
      - "**/examples/**/*.java"
    checks:
      #This is a good check,
      #but sadly IntelliJ doesn't support the required arranging
      #The arrangement option for "keep overloaded methods together" would be needed
      #Enable this check as soon as IntelliJ supports it
      com.puppycrawl.tools.checkstyle.checks.coding.OverloadMethodsDeclarationOrderCheck:
        enabled: false
      #Again a good check, but IntelliJ doesn't support the required arrangement with @return
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTagContinuationIndentationCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck:
        allowedDistance: 8
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocParagraphCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false #Disabled as the check is not working properly (maybe due to \n\r stuff)