# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  verify:
    name: "build & test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Setup"
        uses: "./.github/setup"
      - name: "Build"
        run: "./gradlew classes"
      - name: "Test"
        run: "./gradlew test"
      - name: "Test coverage"
        run: "./gradlew jacocoRootReport jacocoCoverageVerification"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports/jacoco/html/
          retention-days: 2
      - name: "Sonar Qube"
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: "./gradlew sonarqube --info"
      - name: "Stop Gradle deamon"
        if: always()
        run: "./gradlew --stop"
