# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  verify:
    name: "build & test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Setup"
        uses: "./.github/setup"
      - name: "Build"
        run: "./gradlew classes"
      - name: "Test"
        run: "./gradlew test"
      - name: "Test coverage"
        run: "./gradlew jacocoRootReport jacocoCoverageVerification"
      - name: "Sonar Qube"
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: "./gradlew sonarqube --info"
      - name: commit-code-coverage
        if: always()
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_RUNNER_TOKEN }}
        run: |
          ./cc-test-reporter format-coverage build/reports/jacoco/coverage.xml --input-type jacoco
          ./cc-test-reporter upload-coverage  --owner ${{ github.owner }} --repo ${{ github.repository }} --pr ${{ github.pull_request }} --token ${{ secrets.CC_RUNNER_TOKEN }}
      - name: "Stop Gradle deamon"
        if: always()
        run: "./gradlew --stop"
